# Generated by Django 4.2.9 on 2024-02-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='relase_date',
            new_name='release_date',
        ),
    ]
